version = 0.1

[default.deploy.parameters]
stack_name = "route-solver-daily"
resolve_s3 = true
s3_prefix = "route-solver-daily"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ApiBaseUrl=\"https://wecode.outsystems.com/StarDelivery_Ngin/rest/StarDeliveryServices\""
image_repositories = []

[default.global.parameters]
region = "eu-central-1"
